#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Alexander Bartels

# Short bio or description (displayed in the header)
description: Software Engineer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: //www.gravatar.com/avatar/64e5b873a50539535be3b4ed21e3ce22

# Includes an icon in the footer for each username you enter
footer-links:
  github: alexanderbartels
  twitter: BartelsXander

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-54367902-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.alexanderbartels.com/

markdown: kramdown
highlighter: rouge
permalink: /:title/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

include:
    - _redirects
    - Handout-komplett.pdf

